---
- name: user creation play book for Tomcatserver
  hosts: webservers
  tasks:
    - name: Installing java(JDK) (if not present)
      apt:
        name: openjdk-11-jre-headless
        state: present
        update_cache: yes
    - name: creating Tomcat user
      become: yes
      user: 
        name: tomcat
        state: present

    - name: create a directory /opt/tomcat  
      become: yes
      file: 
        path: /opt/tomcat
        state: present
        mode: 0755
        owner: tomcat

    - name: Installing Tomcat latest version (if not present)
      unarchive:
        src: https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.27/bin/apache-tomcat-10.0.27.tar.gz
        dest: /opt/tomcat
        remote_src: yes
        extra_opts: [--strip-components=1]
    - name: creating a service file
      become: yes
      copy: 
        dest: /etc/systemd/system/tomcat.service
        content:
            [Unit]
            Description=Tomcat
            After=network.target
            
            [Service]
            Type=forking
            User=tomcat
            Group=tomcat
            Environment="JAVA_HOME=/usr/lib/jvm/java-1.11.0-openjdk-amd64"
            Environment="JAVA_OPTS=-Djava.security.egd=file:///dev/urandom"
            Environment="CATALINA_BASE=/opt/tomcat"
            Environment="CATALINA_HOME=/opt/tomcat"
            Environment="CATALINA_PID=/opt/tomcat/temp/tomcat.pid"
            Environment="CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC"
            
            ExecStart=/opt/tomcat/bin/startup.sh
            ExecStop=/opt/tomcat/bin/shutdown.sh
            RestartSec=10
            Restart=always

            [Install]
            WantedBy=multi-user.target

    - name: Relod the systemD to re-read configurations
      become: yes
      systemd:
        daemon-reload: yes

    - name: Enable the tomcat service and start
      become: yes
      systemd:
        name: tomcat
        enabled: yes  
        state: started

    - name: allow all access to tcp port 8080
      ufw: 
        rule: allow
        port: 8080
        proto: tcp  
        state: enabled  
